version: '3'
services:
  homeassistant:
    container_name: "ddev-${DDEV_SITENAME}-homeassistant"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./homeassistant:/config
    restart: unless-stopped
    privileged: true
    expose:
      - "8123"
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=8122:8123
      - HTTPS_EXPOSE=8123:8123